#!/usr/bin/env bash

# Copyright © 2023 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

if [ $# -ne 1 ]
then
    printf 'Usage: %s EMAIL\n' "$0" >&2
    exit 1
fi

e="$1"
msmtp -- $e <<EOF
From: $e
To: $e
Disposition-Notification-To: $e
Subject: Test $RANDOM

Hello world!
EOF

# vim:ts=4 sts=4 sw=4 et
